catalog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


urlpatterns = [
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^books/rosman/$', views.BooksRosman.as_view(), name='books_rosman'),
    url(r'^books/eng/$', views.BooksEng.as_view(), name='books_eng'),
    url(r'^books/textbooks/$', views.BooksTextbooks.as_view(), name='books_textbooks'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book_detail'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
    url(r'^book/(?P<pk>\d+)/add_to_cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^merch/(?P<pk>\d+)/add_to_cart/$', views.add_to_cart, name='add_to_cart_merch'),
    #######
    path('merch/<int:pk>', views.MerchandiseDetailView.as_view(), name='merchandise_detail'),
    url(r'^merch/standart-sticks/$', views.MagicStickStandart.as_view(), name='merch_stand_stick'),
    url(r'^merch/metal-sticks/$', views.MagicStickMetal.as_view(), name='merch_metal_stick'),
    url(r'^merch/clothes/$', views.MerchClothes.as_view(), name='merch_clothes'),
    url(r'^merch/hats/$', views.MerchClothesHats.as_view(), name='merch_clothes_hats'),
    url(r'^merch/scarves/$', views.MerchClothesScarves.as_view(), name='merch_clothes_scarves'),
    url(r'^merch/gloves/$', views.MerchClothesGloves.as_view(), name='merch_clothes_gloves'),
    url(r'^merch/ties/$', views.MerchClothesTies.as_view(), name='merch_clothes_ties'),
    url(r'^merch/caps/$', views.MerchClothesCaps.as_view(), name='merch_clothes_caps'),
    url(r'^merch/sweaters/$', views.MerchClothesSweaters.as_view(), name='merch_clothes_sweaters'),
    url(r'^merch/mantle/$', views.MerchClothesMantle.as_view(), name='merch_clothes_mantle'),
    url(r'^merch/socks/$', views.MerchClothesSocks.as_view(), name='merch_clothes_socks'),
    url(r'^merch/tshirt/$', views.MerchClothesTshirts.as_view(), name='merch_clothes_tshirts'),
    url(r'^merch/tshirt/$', views.MerchClothesTshirts.as_view(), name='merch_clothes_tshirts'),
    ######
    url(r'^merch/accessories/$', views.MerchAccessories.as_view(), name='merch_accessories'),
    url(r'^merch/accessories/figurines/$', views.MerchAccessoriesFigurines.as_view(), name='merch_accessories_figurines'),
    url(r'^merch/accessories/pendants/$', views.MerchAccessoriesPendants.as_view(), name='merch_accessories_pendants'),
    url(r'^merch/accessories/notebooks/$', views.MerchAccessoriesNotebooks.as_view(), name='merch_accessories_notebooks'),
    url(r'^merch/accessories/bracelet/$', views.MerchAccessoriesBracelet.as_view(), name='merch_accessories_bracelet'),
    url(r'^merch/accessories/wallet/$', views.MerchAccessoriesWallet.as_view(), name='merch_accessories_wallet'),
    url(r'^merch/accessories/bookmark/$', views.MerchAccessoriesBookmark.as_view(), name='merch_accessories_bookmark'),
    url(r'^merch/accessories/rings/$', views.MerchAccessoriesRings.as_view(), name='merch_accessories_rings'),
    url(r'^merch/accessories/mugs/$', views.MerchAccessoriesMugs.as_view(), name='merch_accessories_mugs'),
    url(r'^merch/accessories/watches/$', views.MerchAccessoriesWatches.as_view(), name='merch_accessories_watches'),
    url(r'^merch/accessories/pencil_cases/$', views.MerchAccessoriesPencilCases.as_view(), name='merch_accessories_pencil_cases'),
    ######
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    ######
    url(r'^cart/$', views.get_cart, name="cart"),
    url(r'^cart/clear', views.clear_cart, name="clear_cart"),
    url(r'^cart/(?P<pk>\d+)/delete/$', views.remove_from_cart, name="delete_item"),
    url(r'^cart/complete', views.cart_complete_order, name="cart_complete_order"),
    ######
    path('/search', views.SearchView.as_view(), name='search_view'),
]

core/urls.py
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^delivery/$', views.delivery, name='delivery'),
    url(r'^sales/$', views.sales, name='sales'),
    url(r'^reviews/$', views.reviews, name='reviews'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.contrib.auth.models import User
from django.urls import reverse  # Для генерации URL переворачиванием URL паттернов
from django.db import models
from datetime import date
import uuid


class Property(models.Model):

    address = models.TextField()

    def __str__(self):

        return self.address


class PropertyImage(models.Model):

    property = models.ForeignKey(Property, related_name="images", on_delete=models.SET_NULL, null=True, blank=True)
    images = models.ImageField(upload_to="images/sliders_images")


class Genre(models.Model):

    """
    Модель, отображающая жанр книги( Научная фантастика и др.)
    """

    name = models.CharField(max_length=200, help_text="Введите жанр книги (Например, Научная Фантастика, Французская Поэзия и др.)")

    def __str__(self):

        """
        Строка для отображения модели Объекта
        """

        return self.name


class Language(models.Model):
    """
    Модель, отображающая язык (Например Русский, Английский, Японский и т.д.)
    """

    name = models.CharField(max_length=200, help_text='Введите оригинальный язык книги (Например Русский, Английский и т.д.)')

    def __str__(self):

        return self.name


class Attachment(models.Model):

    def get_upload_to(instance, filename):

        return 'images/sliders_images/{0}/{1}'.format(Book.id, filename)

    image = models.ImageField(upload_to=get_upload_to, null=True)

    def __str__(self):

        """
        Строка для отображения модели Объекта
        """

        return self.name


class Book(models.Model):

    """
    Модель, отображающая книгу(но не конкретную копию книги).
    """

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key используется потому что у книги может быть один автор, но у автора может быть много книг
    # Автор как строка, а не объект, потому что он еще не объявлен в файле.
    summary = models.TextField(max_length=1000, help_text='Введите описание книги')
    benefits = models.CharField(max_length=1000, help_text='Введите краткое описание книги. Каждую строку отделять ,', null=True)
    thumbnail = models.ImageField(upload_to='images/thumbnails', default="images/thumbnails/default.jpg")
    images = models.ForeignKey(Property, help_text='Загрузите фотографии для слайдера', on_delete=models.CASCADE, null=True, blank=True)
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Выберите жанр для книги')
    # ManyToManyField используется потому что жанр может содержать множество книг. Книги могут относиться к многим жанрам.
    # Класс жанра уже определен, поэтому мы можем указать объект выше.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    price = models.IntegerField(null=True)

    def __str__(self):

        return self.title

    def get_absolute_url(self):

        """
        Возвращает URL-адрес для доступа к конкретному экземпляру книги.
        """

        return reverse('book_detail', args=[str(self.id)])

    def display_genre(self):
        """
        Создаёт строку для жанра. Это необходимо для отображения жанра в Админ-панели
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Жанр'

    def get_images_list(self):

        property = Property.objects.get(address=self.images)
        images_list = property.images.all()
        return images_list

    def get_benefits_list(self):

        try:
            return self.benefits.split(',')
        except AttributeError:
            return ['Этот раздел необходимо заполнить']


class BookInstance(models.Model):

    """
    Модель, представляющая конкретную копию книги (Т.е. которая может быть заимствована из библиотеки).
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Уникальный идентификатор для этой конкретной книги по всей библиотеке')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'На обслуживании'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Статус книги')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):

        return '{0} ({1})'.format(self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):

    """
    Модель, отображающая автора.
    """

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    def get_absolute_url(self):

        return reverse("author_detail", args=[str(self.id)])


    def __str__(self):

        return '{0}, {1}'.format(self.last_name, self.first_name)


    class Meta:
        ordering = ['last_name']


class Merchandise(models.Model):

    """
    Модель, отображающая продукция.
    """

    title = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField(max_length=1000)
    thumbnail = models.ImageField(upload_to='images/merchandise', default="images/merchandise/default.jpg")
    images = models.ForeignKey(Property, help_text='Загрузите фотографии для слайдера', on_delete=models.CASCADE, null=True, blank=True)

    def get_absolute_url(self):

        return reverse("merchandise_detail", args=[str(self.id)])


    def __str__(self):

        return self.title


    def get_images_list(self):

        property = Property.objects.get(address=self.images)
        images_list = property.images.all()
        return images_list

catalog/forms.py
from django import forms
from django.forms import ModelForm
from .models import BookInstance

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from multiupload.fields import MultiImageField
import datetime  # для проверки обновления даты


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Проверка того, что дата не выходит за "нижнюю" границу (не в прошлом).
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Проверка того, что дата не выходит за "верхнюю границу (+4 недели).
        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Возврат "очищенных" данных
        return data


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Проверка того, что дата не в прошлом
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Не забывайте всегда возвращать очищенные данные
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back', ]
        labels = {'due_back': _('Renewal date'), }
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).'), }


class UploadForm(forms.Form):

    attachments = MultiImageField(min_num=1, max_num=5, max_file_size=1024*1024*5)

catalog/templates/catalog/add_to_cart.html
{% extends 'base_generic.html' %}

{% block content %}
    <table>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        {% for item in cart %}
        <tr>
            <td>{{ item.book.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.total_price }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock content %}

catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Authors List</h1>

    {% if author_list %}
        <ul>

            {% for author in author_list %}
            <li>
                <a href='{{ author.get_absolute_url }}'>{{ author }}({{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% else %}Alive today{% endif %})</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>There are no authors in the library.</p>
        {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/item-card.css' %}">
<div class="item-card">   
    <h1 class="item-card_title garry">{{ book.title }}</h1>
    <div class="wrap_product_description">
        <div class="wrap_product_slider">
            <div class="slider_item-main">
                {% for image in book.get_images_list %}
                        <a href="{{ image.images.url }}" data-lightbox="img">
                            <img src="{{ MEDIA_URL }}{{ image.images.url }}" alt="">
                        </a>
                {% endfor %}
            </div>
            <div class="slider_item-nav">
                {% for image in book.get_images_list %}
                    <div class="small_item_slide">
                        <img src="{{ MEDIA_URL }}{{ image.images.url }}" alt="">
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="product_description">
            <div class="product_description_text">
                 <h3 class="product_description_title">Описание</h3> <!--доделать описание продукта -->
                <ul>
                {% if book.get_benefits_list %}
                    {% for benefit in book.get_benefits_list %}
                        <li>{{ benefit }}</li>
                    {% endfor %}
                {% endif %}
                </ul>
            </div>
            <div class="product_description_available">
                <h3 class="product_description_title">Наличие</h3>
                <p>В наличии</p>
            </div>
            <div class="product_description_art">
                <h3 class="product_description_title">Артикул</h3>
                <p>А017</p>
            </div>
            <div class="product_description_price">
                <h3 class="product_description_title">Цена</h3>
                <p>{{ book.price }} руб.</p>
            </div>

            <div class="navigation_count_product">
                <button type="button" id="minus_detail" class="minus_detail">-</button>
                <input type="text" value="1" name="count" class="count_product_detail" id="count_product_detail">
                <button type="button" id="plus_detail" class="plus_detail">+</button>
            </div>
            <div class="product_button_add">
                <button type="button" pk={{ book.id }} data-url="{% url 'add_to_cart' book.id %}" title="Добавить в корзину" name="buy_btn" id="buybtn" class="add_to_basket">
                    Добавить в корзину
                </button>
                {% csrf_token %}
                <button type="submit" name="click_btn" id="clickbtn" class="click_btn">
                    Купить в 1 клик
                </button>
            </div>
        </div>
    </div>
    <div class="product_summary">
        <h1 class="product_summary_title garry">{{ book.title }}</h3>
        <p>{{ book.summary }}</p>
    </div>
</div>

    {% block javacript %}
        <script src="{% static 'js/slick_slider_detail.js' %}"></script>
    {% endblock javacript %}
{% endblock content %}

catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    {% if book_list %}
        <div class='books_list'>
            {% for book in book_list %}
            <div class='books_result'>
                <a href="{{ book.get_absolute_url }}">
                    <img class="thumbnails" src="{{ MEDIA_URL }}{{ book.thumbnail.url }}" alt="">
                    <p class='merch_result-title'>{{ book.title }} {% if book.author %} ({{ book.author }}){% endif %}</p>
                    <p class='merch_result-sum'>{{ book.price }} руб.</p>
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %}
{% block content %}

    <h1>Renew: {{ bookinst.book.title }}</h1>
    <p>Borrower: {{ bookinst.borrower }}
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{ bookinst.due_back }}</p>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_librarian.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> {% if bookinst.is_overdue %}Book is overdue{% endif %} ({{ bookinst.due_back }}) - {{ bookinst.borrower}}
            {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew_book_librarian' bookinst.id %}">Renew</a>{% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> {% if bookinst.is_overdue %}Book is overdue{% endif %} ({{ bookinst.due_back }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock content %}

catalog/templates/catalog/cart.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/item-card.css' %}">

    <form class="wrap_basket_table">
        <div class="top_line_basket_table">
            <span class="name_column_mob_version">Товары</span>
            <span class="name_product_column">Наименование</span>
            <span class="price_product_column">Цена за шт.</span>
            <span class="count_product_column">Количество</span>
            <span class="sum_product_column">Сумма</span>
        </div>
        {% for item in cart %}
            <div class="line_basket_table">
                <div class="product">
                    <div class="name">
                        <div class="image_product">
                            <img src="{{ MEDIA_URL }}{{ item.product.thumbnail.url }}" alt="">
                        </div>
                        <div class="name_text">
                            <a href="#" class="title_descr_product">{{ item.product.title }}</a>
                            <div class="art">Артикул: 01350622</div>
                        </div>
                    </div>
                    <div class="price_product">
                        <span class="price basket-item-price-current-text">${{ item.product.price }}</i></span>
                    </div>
                    <div class="navigation_count_product">
                        <button id="minus" type="button" class="minus" pk={{ item.product.id }} data-url="{% url 'delete_item' item.product.id %}" title="Уменьшить на 1 единицу товара">-</button>
                        <input type="text" value={{ item.quantity }} name="count" class="count_product" id="count_product">
                        <button id="plus" type="button" class="plus" pk={{ item.product.id }} data-url="{% url 'add_to_cart' item.product.id %}" title="Увеличить на 1 единицу товара">+</button>
                        {% csrf_token %}
                        {% if not item.product.genre %}<input type="hidden" value="True" name="merch" class="merchandise">{% endif %}
                    </div>
                    <div class="sum_box">
                        <span class="name_column_mob_version">Сумма <i class="fas fa-ruble-sign"></i>:</span>
                        <span class="summa basket-coupon-block-total-price-current">${{ item.total_price }}</span>
                    </div>
                </div>
                <a href="{% url 'delete_item' item.product.id %}" class="remove_product" title="Удалить товар из корзины">
                    X
                </a>
            </div> 
        {% endfor %}
        <div class="summa_box">
            <span class="title_result_list_item">К оплате:</span>
            <span class="value_result_list_item summa_all">${{ cart.summary }}</i></span>
        </div>
        <div class="btns_table_line">
            <a href="{% url 'clear_cart' %}" class="btns_table_line_sub" title="Очистить корзину">
                Очистить корзину
            </a>
            <a href="{% url 'cart_complete_order' %}" class="btns_table_line_sub">Оформить заказ</a>
        </div>
    </div>
    </form>


{% endblock content %}

{% block javascript %}
    <script src="{% static 'js/changePricesAndSummary.js' %}"></script>
{% endblock javascript %}

catalog/templates/catalog/merchandise_detail.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/item-card.css' %}">
<div class="item-card">   
    <h1 class="item-card_title garry">{{ merchandise.title }}</h1>
    <div class="wrap_product_description">
        <div class="wrap_product_slider">
            <div class="slider_item-main">
                {% for image in merchandise.get_images_list %}
                        <a href="{{ merchandise.images.url }}" data-lightbox="img">
                            <img src="{{ MEDIA_URL }}{{ image.images.url }}" alt="">
                        </a>
                {% endfor %}
            </div>
            <div class="slider_item-nav">
                {% for image in merchandise.get_images_list %}
                    <div class="small_item_slide">
                        <img src="{{ MEDIA_URL }}{{ image.images.url }}" alt="">
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="product_description">
            <div class="product_description_text">
                 <h3 class="product_description_title">Описание</h3> <!--доделать описание продукта -->
                <ul>

                </ul>
            </div>
            <div class="product_description_available">
                <h3 class="product_description_title">Наличие</h3>
                <p>В наличии</p>
            </div>
            <div class="product_description_art">
                <h3 class="product_description_title">Артикул</h3>
                <p>А017</p>
            </div>
            <div class="product_description_price">
                <h3 class="product_description_title">Цена</h3>
                <p>{{ merchandise.price }} руб.</p>
            </div>

            <div class="navigation_count_product">
                <button type="button" id="minus_detail" class="minus_detail">-</button>
                <input type="text" value="1" name="count" class="count_product_detail" id="count_product">
                <button type="button" id="plus_detail" class="plus_detail">+</button>
            </div>
            <div class="product_button_add">
                <button type="button" pk={{ merchandise.id }} data-url="{% url 'add_to_cart_merch' merchandise.id %}" title="Добавить в корзину" name="buy_btn" id="buybtn" class="add_to_basket">
                    Добавить в корзину
                </button>
                <input type="hidden" value="True" name="merch" class="merchandise">
                {% csrf_token %}
                <button type="submit" name="click_btn" id="clickbtn" class="click_btn">
                    Купить в 1 клик
                </button>
            </div>
        </div>
    </div>
    <div class="product_summary">
        <h1 class="product_summary_title garry">{{ merchandise.title }}</h3>
        <p>{{ merchandise.summary }}</p>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/search_results.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Результаты поиска:</h1>

    {% if results %}
        <div class="search-result-list">
            {% for result in results %}
            <div class='search-result'>
                <a href="{{ result.get_absolute_url }}">
                    <img class="thumbnails" src="{{ MEDIA_URL }}{{ result.thumbnail.url }}" alt="">
                    <p class='merch_result-title'>{{ result.title }} {% if result.author %} ({{ result.author }}){% endif %}</p>
                    <p class='merch_result-sum'>{{ result.price }} руб.</p>
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}